version: '3.8'

services:
  fastapi:
    build: api/
    container_name: fastapi-app
    ports:
      - "3000:3000"  # ✅ Add this line
    restart: always

  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - fastapi