AWSTemplateFormatVersion: '2010-09-09'
Description: Generic AWS CloudFormation Template

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (e.g., dev, test, prod)

Resources:
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-sample-bucket'

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref SampleS3Bucket