ARG FUNCTION_DIR="/app"

# --- Stage 1: Use Playwright image ---
FROM mcr.microsoft.com/playwright/python:v1.44.0-focal AS builder

ARG FUNCTION_DIR
RUN mkdir -p ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}

# Copy app and install dependencies
COPY app/requirements.txt .
COPY app/ ${FUNCTION_DIR}

RUN pip install --upgrade pip && \
    pip install --target ${FUNCTION_DIR} -r requirements.txt

# --- Stage 2: Final Lambda Image ---
FROM mcr.microsoft.com/playwright/python:v1.44.0-focal

ARG FUNCTION_DIR
WORKDIR ${FUNCTION_DIR}

COPY --from=builder ${FUNCTION_DIR} ${FUNCTION_DIR}

# Install AWS Lambda Runtime Interface Client
RUN pip install gunicorn[gevent] uvicorn[standard]

RUN python -m playwright install chromium

# Optional: Add RIE for local testing
# ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/local/bin/aws-lambda-rie
# RUN chmod +x /usr/local/bin/aws-lambda-rie

# Use Python 3 binary from system
# ENTRYPOINT [ "python3", "-m", "awslambdaric" ]
CMD ["gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "--workers", "4", "--bind", "0.0.0.0:3000"]